const architecture = [
    {
        id: 44,
        src: './pictures/Architecture/GreywoodHouse/_SRN1203-Edit.jpg',
        alt: 'gh1',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 45,
        src: './pictures/Architecture/GreywoodHouse/_SRN1208-Edit.jpg',
        alt: 'gh2',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 46,
        src: './pictures/Architecture/GreywoodHouse/_SRN1211-Edit.jpg',
        alt: 'gh3',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 47,
        src: './pictures/Architecture/GreywoodHouse/_SRN1226.jpg',
        alt: 'gh4',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 48,
        src: './pictures/Architecture/GreywoodHouse/_SRN1234-Edit1.jpg',
        alt: 'gh5',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 49,
        src: './pictures/Architecture/GreywoodHouse/_SRN1261.jpg',
        alt: 'gh6',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 50,
        src: './pictures/Architecture/GreywoodHouse/_SRN1266.jpg',
        alt: 'gh7',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 51,
        src: './pictures/Architecture/GreywoodHouse/_SRN1276-Edit.jpg',
        alt: 'gh8',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 52,
        src: './pictures/Architecture/GreywoodHouse/_SRN1288-Edit.jpg',
        alt: 'gh9',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 53,
        src: './pictures/Architecture/GreywoodHouse/_SRN1308.jpg',
        alt: 'gh10',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 54,
        src: './pictures/Architecture/GreywoodHouse/_SRN1333-Edit.jpg',
        alt: 'gh11',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 55,
        src: './pictures/Architecture/GreywoodHouse/_SRN1339.jpg',
        alt: 'gh12',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 56,
        src: './pictures/Architecture/GreywoodHouse/_SRN1343-Edit.jpg',
        alt: 'gh13',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 57,
        src: './pictures/Architecture/GreywoodHouse/_SRN1344-2.jpg',
        alt: 'gh14',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 58,
        src: './pictures/Architecture/GreywoodHouse/_SRN1369.jpg',
        alt: 'gh15',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 59,
        src: './pictures/Architecture/GreywoodHouse/cover_SRN1261.jpg',
        alt: 'gh16',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 60,
        src: './pictures/Architecture/GreywoodHouse/WickerBasket.gif',
        alt: 'gh17',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 61,
        src: './pictures/Architecture/GreywoodHouse/_SRN1234.jpg',
        alt: 'gh18',
        category: 'architecture',
        subcategory: 'greywordHouse',
        best: 0,
    },
    {
        id: 62,
        src: './pictures/Architecture/Arch/2_2.jpg',
        alt: 'anda1',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 63,
        src: './pictures/Architecture/Arch/4.jpeg',
        alt: 'anda2',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 64,
        src: './pictures/Architecture/Arch/7.jpg',
        alt: 'anda3',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 65,
        src: './pictures/Architecture/Arch/09_SRN7153.jpg',
        alt: 'anda4',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 66,
        src: './pictures/Architecture/Arch/12.jpg',
        alt: 'anda5',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 67,
        src: './pictures/Architecture/Arch/2020_Andalucia_architecture.jpg',
        alt: 'anda6',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 68,
        src: './pictures/Architecture/Arch/2020_Andalucia_catreflection.jpg',
        alt: 'anda7',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 69, 
        src: './pictures/Architecture/Arch/2020_Andalucia_connection.jpg',
        alt: 'anda8',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 70,
        src: './pictures/Architecture/Arch/2020_Andalucia_goldenhour.jpg',
        alt: 'anda9',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 71,
        src: './pictures/Architecture/Arch/2020_Andalucia_mosque-church.jpg',
        alt: 'anda10',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 72,
        src: './pictures/Architecture/Arch/2020_Andalucia_riverslopes.jpg',
        alt: 'anda11',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 73,
        src: './pictures/Architecture/Arch/2020_Andalucia_stained-columns.jpg',
        alt: 'anda12',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    },
    {
        id: 74,
        src: './pictures/Architecture/Arch/SRN02794.jpg',
        alt: 'anda13',
        category: 'architecture',
        subcategory: 'andalucia',
        best: 0,
    }
];