const artwork = [
    {
        id: 75,
        src: './pictures/Artworks/Churchgate-station-mumbai.jpg',
        alt: 'artworks1',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 76,
        src: './pictures/Artworks/Darkroom-for-housing.jpg',
        alt: 'artworks2',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 77,
        src: './pictures/Artworks/Ducktails.jpg',
        alt: 'artworks3',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 78,
        src: './pictures/Artworks/Exospheres.jpg',
        alt: 'artworks4',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 79,
        src: './pictures/Artworks/Next-door-stangers-.jpg',
        alt: 'artworks5',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 80,
        src: './pictures/Artworks/Postcard_of_a_figmental_biosphere.jpg',
        alt: 'artworks6',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 81,
        src: './pictures/Artworks/Time-capsule-of-mumbai.jpg',
        alt: 'artworks7',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 82,
        src: './pictures/Artworks/Time-travel.png',
        alt: 'artworks8',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 83,
        src: './pictures/Artworks/When-pigs-fly.png',
        alt: 'artworks9',
        category: 'artworks',
        subcategory: '',
        best: 0,
    },
    {
        id: 84,
        src: './pictures/Artworks/Whirlpool-mind.jpg',
        alt: 'artworks10',
        category: 'artworks',
        subcategory: '',
        best: 0,
    }
];