const data = [
    {
        id: 1,
        src: './pictures/bestWork/2020_portfolio_202.jpg',
        alt: 'red saree',
        category: 'photography',
        subcategory: 'saree',
        best: 0,

    },
    {
        id: 2,
        src: './pictures/bestWork/2020_portfolio_203.jpg',
        alt: 'red saree',
        category: 'photography',
        subcategory: 'saree',
        best: 0,
    },
    {
        id: 3,
        src: './pictures/bestWork/2020_portfolio_204.jpg',
        alt: 'red saree',
        category: 'photography',
        subcategory: 'saree',
        best: 0,
    },
    {
        id: 4,
        src: './pictures/bestWork/2020_portfolio_205.jpg',
        alt: 'red saree',
        category: 'photography',
        subcategory: 'saree',
        best: 0,
    },
    {
        id: 5,
        src: './pictures/bestWork/2020_portfolio_206.jpg',
        alt: 'green saree',
        category: 'photography',
        subcategory: 'saree',
        best: 0,
    },
    {
        id: 6,
        src: './pictures/bestWork/2020_portfolio_207.jpg',
        alt: 'green saree',
        category: 'photography',
        subcategory: 'saree',
        best: 0,
    },
    {
        id: 7,
        src: './pictures/bestWork/2020_portfolio_208.jpg',
        alt: 'yellow saree',
        category: 'photography',
        subcategory: 'saree',
        best: 0,
    },
    {
        id: 8,
        src: './pictures/bestWork/2020_portfolio_209.jpg',
        alt: 'yellow saree',
        category: 'photography',
        subcategory: 'saree',
        best: 0,
    },
    {
        id: 9,
        src: './pictures/bestWork/2020_portfolio_2010.jpg',
        alt: 'domestication1',
        category: 'photography',
        subcategory: 'domestication',
        best: 0,
    },
    {
        id: 10,
        src: './pictures/bestWork/2020_portfolio_2011.jpg',
        alt: 'domestication2',
        category: 'photography',
        subcategory: 'domestication',
        best: 0,
    },
    {
        id: 11,
        src: './pictures/bestWork/2020_portfolio_2012.jpg',
        alt: 'domestication3',
        category: 'photography',
        subcategory: 'domestication',
        best: 0,
    }
];
